# Generated by Django 3.0.4 on 2020-08-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='address',
            field=models.CharField(default='address', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostAnAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('subject', models.CharField(default='English', max_length=100)),
                ('tuition_level', models.CharField(default='O Level', max_length=100)),
                ('tuition_type', models.CharField(max_length=100, null=True)),
                ('hours_per_day', models.IntegerField()),
                ('days_per_week', models.IntegerField()),
                ('estimated_salary', models.IntegerField()),
                ('tutor_gender', models.CharField(default='Male/Fe-Male', max_length=200)),
                ('academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.Academy')),
            ],
        ),
    ]
