# Generated by Django 3.0.4 on 2020-08-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20200831_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postanad',
            old_name='academy',
            new_name='academyUser',
        ),
    ]
