# Generated by Django 3.0.4 on 2020-09-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0013_invitaions_by_academy'),
        ('academy', '0003_auto_20200831_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('inivitaion_by_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor')),
                ('student_ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.PostAnAd')),
            ],
        ),
    ]
