# Generated by Django 3.0.4 on 2020-09-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20200912_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitations',
            old_name='tutor_ad',
            new_name='academy_ad',
        ),
    ]
