# Generated by Django 3.0.4 on 2020-09-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20200913_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postanad',
            name='tuition_type',
        ),
    ]
