# Generated by Django 3.0.4 on 2020-04-14 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorUser', models.CharField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('tuition_level', models.CharField(max_length=300)),
                ('can_travel', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=300)),
                ('estimated_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100, null=True)),
                ('cnic', models.CharField(max_length=13, null=True)),
                ('verified', models.BooleanField(default=False, null=True)),
                ('verification_sent', models.BooleanField(default=False)),
                ('total_ads', models.IntegerField(default=0)),
                ('ads_deleted', models.IntegerField(default=0)),
                ('invitations_sent', models.IntegerField(default=0)),
                ('invitations_sent_accepted', models.IntegerField(default=0)),
                ('invitations_sent_rejected', models.IntegerField(default=0)),
                ('invitations_recieved', models.IntegerField(default=0)),
                ('invitations_recieved_accepted', models.IntegerField(default=0)),
                ('invitations_recieved_rejected', models.IntegerField(default=0)),
                ('ad_post_count', models.IntegerField(default=0)),
                ('profile_complete', models.BooleanField(default=False)),
                ('user_image', models.ImageField(default='user_profile_default.jpg', upload_to='profile_pics_tutors')),
                ('tutor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitaions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('inivitaion_by_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('tutor_ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.PostAnAd')),
            ],
        ),
        migrations.CreateModel(
            name='AboutAndQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=300)),
                ('highest_qual', models.CharField(max_length=100)),
                ('highest_qual_inst', models.CharField(max_length=100)),
                ('secondary_qaul', models.CharField(max_length=100)),
                ('secondary_qaul_inst', models.CharField(max_length=100)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor')),
            ],
        ),
    ]
