# Generated by Django 3.0.4 on 2020-04-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanad',
            name='tutorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor'),
        ),
    ]
