# Generated by Django 3.0.4 on 2020-04-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20200414_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutandqualifications',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutandqualifications',
            name='tagline',
        ),
        migrations.AddField(
            model_name='tutor',
            name='about',
            field=models.CharField(default='about tutor', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tagline',
            field=models.CharField(default='tagline', max_length=50),
            preserve_default=False,
        ),
    ]
