# Generated by Django 3.0.4 on 2020-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='highist_qual',
            field=models.FileField(upload_to=''),
        ),
    ]
