# Generated by Django 3.0.4 on 2020-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_auto_20200415_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='highist_qual',
            field=models.ImageField(upload_to=''),
        ),
    ]
