# Generated by Django 3.0.4 on 2020-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_auto_20200416_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='profile_complete',
            new_name='about_complete',
        ),
        migrations.AddField(
            model_name='tutor',
            name='qual_complete',
            field=models.BooleanField(default=False),
        ),
    ]
