# Generated by Django 3.0.4 on 2020-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_auto_20200416_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
