# Generated by Django 3.0.4 on 2020-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_postanad_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanad',
            name='tuition_type',
            field=models.CharField(default='Home Tuition', max_length=100, null=True),
        ),
    ]
