# Generated by Django 3.0.4 on 2020-06-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_phone'),
        ('tutors', '0009_postanad_tuition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanad',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='students.Student'),
        ),
    ]
