# Generated by Django 3.0.4 on 2020-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textArea', models.TextField(default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostAnAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='English', max_length=100)),
                ('tuition_level', models.CharField(default='O Level', max_length=100)),
                ('tuition_type', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=300)),
                ('hours_per_day', models.IntegerField()),
                ('days_per_week', models.IntegerField()),
                ('estimated_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='first name', max_length=100)),
                ('last_name', models.CharField(default='last name', max_length=100)),
                ('total_ads', models.IntegerField(default=0)),
                ('ads_deleted', models.IntegerField(default=0)),
                ('profile_complete', models.BooleanField(default=False)),
                ('invitations_sent', models.IntegerField(default=0)),
                ('invitations_sent_accepted', models.IntegerField(default=0)),
                ('invitations_sent_rejected', models.IntegerField(default=0)),
                ('invitations_recieved', models.IntegerField(default=0)),
                ('invitations_recieved_accepted', models.IntegerField(default=0)),
                ('invitations_recieved_rejected', models.IntegerField(default=0)),
                ('ad_post_count', models.IntegerField(default=0)),
                ('user_image', models.ImageField(default='user_profile_default.jpg', upload_to='profile_pics_stds')),
            ],
        ),
        migrations.CreateModel(
            name='TutorInvitaions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('invitation_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
