# Generated by Django 3.0.4 on 2020-04-14 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstudent',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='postanad',
            name='studentUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorinvitaions',
            name='inivitaion_by_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.Tutor'),
        ),
        migrations.AddField(
            model_name='tutorinvitaions',
            name='student_ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.PostAnAd'),
        ),
    ]
