# Generated by Django 3.0.4 on 2020-04-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
