# Generated by Django 3.0.4 on 2020-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_postanad_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
