# Generated by Django 3.0.4 on 2020-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_postanad_likes'),
        ('students', '0008_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanad',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='tutors.Tutor'),
        ),
    ]
