# Generated by Django 3.0.4 on 2020-06-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_postanad_likes'),
        ('students', '0009_postanad_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('tutors', models.ManyToManyField(blank=True, related_name='wishlist', to='tutors.Tutor')),
            ],
        ),
    ]
