# Generated by Django 3.0.4 on 2020-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_postanad_likes'),
        ('students', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='wishlist_tutors', to='tutors.Tutor'),
        ),
    ]
