# Generated by Django 2.2.3 on 2020-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_wishlist_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanad',
            name='tutor_gender',
            field=models.CharField(default='Any', max_length=200),
        ),
    ]
