# Generated by Django 3.0.4 on 2020-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_postanad_tutor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanad',
            name='tutor_gender',
            field=models.CharField(default='Male/Fe-Male', max_length=200),
        ),
    ]
